apiVersion: v1
kind: Service
metadata:
  name: math
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: math
spec:
  selector:
    app: math
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math
  template:
    metadata:
      labels:
        app: math
        version: v1
    spec:
      containers:
        - name: math
          image: jaimesalas/math-api:v1
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math
  template:
    metadata:
      labels:
        app: math
        version: v2
    spec:
      containers:
        - name: math
          image: jaimesalas/math-api:v2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"
          ports:
            - containerPort: 80
