def image 

pipeline {
    agent any
    stages {
        stage('Build front image') {
            steps {
                script {
                    front = docker.build(
                        "jaimesalas/front",
                        "--pull -f $WORKSPACE/06_declarative_pipelines_e2e_refactor/02_running_e2e_with_docker/front/Dockerfile $WORKSPACE/06_declarative_pipelines_e2e_refactor/02_running_e2e_with_docker/front"
                    )
                }
            }
        }
        stage('Build e2e image') {
            steps {
                script {
                    e2e = docker.build(
                        "jaimesalas/front",
                        "--pull -f $WORKSPACE/06_declarative_pipelines_e2e_refactor/02_running_e2e_with_docker/e2e/Dockerfile $WORKSPACE/06_declarative_pipelines_e2e_refactor/02_running_e2e_with_docker/e2e"
                    )
                }
            }
        }
    }
}