apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: math
spec:
  hosts:
    - "*"
  gateways:
    - math-gateway
  http:
    - route:
        - destination:
            host: math
            subset: v1
          weight: 80
        - destination:
            host: math
            subset: v2
          weight: 20
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: math
spec:
  host: math
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
