Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
  end
  
  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "docker"
  config.vm.provision "shell",  path: "provision.sh"
end
