apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lc-cluster
  region: eu-west-3
  version: "1.18"

managedNodeGroups:
  - name: lc-nodes
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
